application:
  appId: vulnerable-web-app
  assetId: vulnerable-web-app
  release: major
  appName: "Test app 1"
  sdlcType: EDM
  appType: Webapp
  webservice: false
  restApi: true
  microservice: false
  projectLanguage: Java
  frameworks: 
   - Spring security
   - Hibernate
  platformVersion: Java 8
  buildSystem: Maven
  riskMatrixRevision: Rev1.0
  sourceFilePattern: ".*\\+\\+\\+.*(\\.java|\\.jsp)+.*"
  sensitivePackagePattern: ".*(\\+\\+\\+.*(com\\/example\\/security)).*"
  fileChangeThreshold: 20
environment:
  scm: "bitbucket"
  scmOwner: "sig-devsecops"
  scmRepositoryName: "vulnerable-web-app"
  scmBranchName: <<SCM_BRANCH_NAME>>
  bitbucketApiUrl: "https://api.bitbucket.org/2.0/repositories/"
  bitbucketUserName: <<BITBUCKET_USERNAME>>
  bitbucketPassword: <<BITBUCKET_PASSWORD>>
  jiraProjectName: <<JIRA_PROJECT_NAME>>
  jiraIssuesQuery: <<JIRA_ISSUES_QUERY>>
  jiraApiUrl: <<JIRA_API_URL>>
  jiraUserName: <<JIRA_USERNAME>>
  jiraAuthToken: <<JIRA_AUTH_TOKEN>>
